[project]
name = "crypto-currency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent>=0.1.3",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.19",
    "streamlit>=1.46.0",
    "streamlit-autorefresh>=1.0.1",
]
